name: Documentation generation CI
on:
push:
branches: [ main ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Doxygen Action C
uses: mattnotmitt/doxygen-action@v1.3.1
with:
working-directory: '.'
doxyfile-path: '../../Doxyfile'
- name: Doxygen Action C++
uses: mattnotmitt/doxygen-action@v1.3.1
with:
working-directory: '.'
doxyfile-path: '../../Doxyfile'
- name: Set up JDK 8
uses: actions/setup-java@v2
with:
java-version: '8'
distribution: 'adopt'- name: Javadoc Action
run: ant -noinput -buildfile build.xml javadoc
- name: Tidy up the javadocs
id: tidy
uses: cicirello/javadoc-cleanup@v1
with:
path-to-root: doc/javadoc
- name: Upload Output Directory
uses: actions/upload-artifact@v2
with:
name: doc-files
path: doc
retention-days: 1
copy:
runs-on: ubuntu-latest
needs: build
steps:
- uses: actions/checkout@v2
with:
ref: gh-pages
- name: Download Output Directory
uses: actions/download-artifact@v2
with:
name: doc-files
path: doc
- name: Commit changes
uses: EndBug/add-and-commit@v7
with:
author_name: Carl Timmer
author_email: timmer@jlab.org
message: 'Update docs'
branch: gh-pages
add: '["docDir/doxygen/C/html/*", "docDir/doxygen/CC/html/*", "docDir/javadoc/",
"docDir/users_guide/Users_Guide.pdf"]'